### ISSUE TITLE
"Drag to command prompt window"

### ISSUE THREAD

**Issue by Enferlain** [weareblahs/WSAtools#2]
![image](https://user-images.githubusercontent.com/15861396/141680756-0d1d515a-81ed-4627-ac9e-57ba3aa35a6e.png)

What command prompt window? There's nothing like that throughout the entire wsatools installation and running

**Comment by weareblahs** [comment]
For `InstallXAPK`, you have to press a key to continue, then when you see this:
![image](https://user-images.githubusercontent.com/37889443/141681381-516dc3d3-5241-4443-a09c-6c84d0e6b404.png)
drag and drop the `xapk` file to this window. Or if you want, copy the path then paste it there.
